"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/Button";
import { Card, CardBody, CardHeader } from "@/components/ui/Card";
import { api } from "@/lib/api-client";
import { HOP_DEPTH_FALLBACK, type ChainValue } from "@/lib/constants";
import type { Chain, TraceResult } from "@/lib/types";

export function TraceForm({ onResult, onError, loading, setLoading }: { onResult: (result: TraceResult) => void; onError: (message: string) => void; loading: boolean; setLoading: (value: boolean) => void }) {
  const [address, setAddress] = useState(""); const [chain, setChain] = useState<ChainValue>("ethereum"); const [hopDepth, setHopDepth] = useState<number>(HOP_DEPTH_FALLBACK.default); const [caseRef, setCaseRef] = useState(""); const [demoSubjects, setDemoSubjects] = useState<Record<string,string>>({}); const [touched, setTouched] = useState(false);
  useEffect(() => { api.demoSubjects().then((payload) => setDemoSubjects(payload.subjects[chain] ?? {})).catch(() => setDemoSubjects({})); }, [chain]);
  const valid = address.trim().length > 0;
  async function submit() { setTouched(true); if (!valid) return; setLoading(true); onError(""); try { onResult(await api.createTrace({ address: address.trim(), chain: chain as Chain, hop_depth: hopDepth, direction: "out", data_mode: "mock", case_ref: caseRef.trim() || null })); } catch (error) { onError(error instanceof Error ? error.message : "Trace failed."); } finally { setLoading(false); } }
  return <Card className="glass overflow-hidden rounded-3xl"><div className="h-1 bg-gradient-to-r from-blue-600 via-violet-500 to-pink-400" /><CardHeader title="Start Investigation" subtitle="Define a subject and trace parameters." /><CardBody className="flex flex-col gap-5"><div><label htmlFor="wallet-address" className="mb-2 block text-xs font-semibold text-vt-text-muted">Wallet Address</label><input id="wallet-address" value={address} onChange={(e) => setAddress(e.target.value)} onBlur={() => setTouched(true)} placeholder="0x... or paste address" spellCheck={false} className="vt-mono w-full rounded-2xl border border-vt-border bg-white/60 px-4 py-3 text-sm outline-none focus:border-vt-accent" aria-invalid={touched && !valid} />{touched && !valid && <p className="mt-2 text-xs text-vt-error">Enter a wallet address to continue.</p>}<div className="mt-3 flex flex-wrap gap-2">{Object.entries(demoSubjects).map(([name,value]) => <Button key={name} type="button" variant="secondary" className="text-xs" onClick={() => setAddress(value)}>Load {name.replaceAll("_", " ")}</Button>)}</div></div><div className="grid gap-4 sm:grid-cols-3"><div><label htmlFor="chain" className="mb-2 block text-xs font-semibold text-vt-text-muted">Network</label><select id="chain" value={chain} onChange={(e) => setChain(e.target.value as ChainValue)} className="w-full rounded-2xl border border-vt-border bg-white/60 px-4 py-3 text-sm"><option value="ethereum">Ethereum</option><option value="tron">Tron</option><option value="bitcoin" disabled>Bitcoin · roadmap</option></select></div><div><label htmlFor="hop-depth" className="mb-2 block text-xs font-semibold text-vt-text-muted">Trace Depth <span className="text-vt-accent">{hopDepth} hops</span></label><input id="hop-depth" type="range" min={1} max={6} value={hopDepth} onChange={(e) => setHopDepth(Number(e.target.value))} className="mt-3 w-full accent-vt-accent" /></div><div><label htmlFor="case-ref" className="mb-2 block text-xs font-semibold text-vt-text-muted">Case Reference <span className="font-normal">(optional)</span></label><input id="case-ref" value={caseRef} onChange={(e) => setCaseRef(e.target.value)} placeholder="e.g. Case #SIH26182" className="w-full rounded-2xl border border-vt-border bg-white/60 px-4 py-3 text-sm" /></div></div><div className="flex flex-wrap items-center justify-between gap-3"><div className="text-xs text-vt-text-faint">Demo mode is explicitly labelled in results.</div><div className="flex gap-2"><Button type="button" variant="secondary" onClick={() => navigator.clipboard?.readText().then(setAddress).catch(() => undefined)}>Paste</Button><Button type="button" variant="secondary" onClick={() => setAddress(Object.values(demoSubjects)[0] ?? "")}>Load Demo</Button><Button type="button" disabled={!valid || loading} onClick={submit}>{loading ? "Tracing..." : "Start Investigation →"}</Button></div></div></CardBody></Card>;
}
