"""initial schema

Revision ID: d7e3f699d889
Revises:
Create Date: 2026-09-18 11:18:02.079123
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.database.types

revision: str = "d7e3f699d889"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_response_cache",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cache_key", sa.String(length=255), nullable=False),
        sa.Column("chain", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("request_params", app.database.types.JSONType(), nullable=False),
        sa.Column("response_body", app.database.types.JSONType(), nullable=False),
        sa.Column("http_status", sa.SmallInteger(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_snapshot", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "chain IN ('ethereum', 'tron', 'bitcoin', 'bnb', 'solana', 'polygon')",
            name="ck_api_cache_chain",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cache_key"),
    )
    with op.batch_alter_table("api_response_cache", schema=None) as batch_op:
        batch_op.create_index("ix_api_cache_expiry", ["expires_at"], unique=False)

    op.create_table(
        "ml_experiments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("algorithm", sa.String(length=64), nullable=False),
        sa.Column("feature_set_version", sa.String(length=32), nullable=False),
        sa.Column("train_rows", sa.Integer(), nullable=True),
        sa.Column("test_rows", sa.Integer(), nullable=True),
        sa.Column("split_strategy", sa.String(length=64), nullable=True),
        sa.Column("metrics", app.database.types.JSONType(), nullable=True),
        sa.Column("artifact_path", sa.String(length=512), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("agency", sa.String(length=255), nullable=True),
        sa.Column("designation", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('investigator', 'analyst', 'admin')", name="ck_users_role"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "vasps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("legal_entity", sa.String(length=255), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("jurisdiction", sa.String(length=8), nullable=True),
        sa.Column("is_fiu_ind_registered", sa.Boolean(), nullable=True),
        sa.Column("website", sa.String(length=512), nullable=True),
        sa.Column("nodal_officer_channel", sa.String(length=512), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('exchange', 'custodial_wallet', 'payment_processor', 'otc_desk', 'broker')",
            name="ck_vasps_kind",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chain", sa.String(length=16), nullable=False),
        sa.Column("address", sa.String(length=128), nullable=False),
        sa.Column("address_display", sa.String(length=128), nullable=True),
        sa.Column("is_contract", sa.Boolean(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tx_count_observed", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "chain IN ('ethereum', 'tron', 'bitcoin', 'bnb', 'solana', 'polygon')",
            name="ck_wallets_chain",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chain", "address", name="uq_wallets_chain_address"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("metadata", app.database.types.JSONType(), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index("ix_audit_created", ["created_at"], unique=False)
        batch_op.create_index("ix_audit_target", ["target_type", "target_id"], unique=False)
        batch_op.create_index("ix_audit_user", ["user_id", "created_at"], unique=False)

    op.create_table(
        "cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_ref", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('open', 'under_review', 'closed')", name="ck_cases_status"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_ref"),
    )
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.create_index("ix_cases_status_created", ["status", "created_at"], unique=False)

    op.create_table(
        "label_dataset_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("chain", sa.String(length=16), nullable=True),
        sa.Column("source_manifest", app.database.types.JSONType(), nullable=False),
        sa.Column("vasp_address_count", sa.Integer(), nullable=False),
        sa.Column("risk_entity_count", sa.Integer(), nullable=False),
        sa.Column("imported_by", sa.Uuid(), nullable=True),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("integrity_report", app.database.types.JSONType(), nullable=True),
        sa.CheckConstraint(
            "chain IN ('ethereum', 'tron', 'bitcoin', 'bnb', 'solana', 'polygon')",
            name="ck_label_versions_chain",
        ),
        sa.ForeignKeyConstraint(
            ["imported_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "token_transfers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chain", sa.String(length=16), nullable=False),
        sa.Column("tx_hash", sa.String(length=128), nullable=False),
        sa.Column("log_index", sa.Integer(), nullable=True),
        sa.Column("block_number", sa.BigInteger(), nullable=True),
        sa.Column("block_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("from_address", sa.String(length=128), nullable=False),
        sa.Column("to_address", sa.String(length=128), nullable=False),
        sa.Column("asset_symbol", sa.String(length=32), nullable=False),
        sa.Column("asset_contract", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("amount_raw", sa.String(length=80), nullable=False),
        sa.Column("decimals", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("fee", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("provenance", sa.String(length=16), nullable=False),
        sa.Column("raw_ref", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "chain IN ('ethereum', 'tron', 'bitcoin', 'bnb', 'solana', 'polygon')",
            name="ck_token_transfers_chain",
        ),
        sa.CheckConstraint(
            "provenance IN ('live_api', 'cached', 'mock_demo', 'mixed')",
            name="ck_token_transfers_provenance",
        ),
        sa.CheckConstraint("status IN ('success', 'failed')", name="ck_token_transfers_status"),
        sa.ForeignKeyConstraint(["raw_ref"], ["api_response_cache.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chain", "tx_hash", "log_index", name="uq_token_transfers_identity"),
    )
    with op.batch_alter_table("token_transfers", schema=None) as batch_op:
        batch_op.create_index(
            "ix_token_transfers_contract", ["chain", "asset_contract"], unique=False
        )
        batch_op.create_index(
            "ix_token_transfers_from", ["chain", "from_address", "block_timestamp"], unique=False
        )
        batch_op.create_index(
            "ix_token_transfers_to", ["chain", "to_address", "block_timestamp"], unique=False
        )

    op.create_table(
        "transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chain", sa.String(length=16), nullable=False),
        sa.Column("tx_hash", sa.String(length=128), nullable=False),
        sa.Column("block_number", sa.BigInteger(), nullable=True),
        sa.Column("block_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("from_address", sa.String(length=128), nullable=False),
        sa.Column("to_address", sa.String(length=128), nullable=False),
        sa.Column("asset_symbol", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("amount_raw", sa.String(length=80), nullable=False),
        sa.Column("decimals", sa.SmallInteger(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("fee", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("provenance", sa.String(length=16), nullable=False),
        sa.Column("raw_ref", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "chain IN ('ethereum', 'tron', 'bitcoin', 'bnb', 'solana', 'polygon')",
            name="ck_transactions_chain",
        ),
        sa.CheckConstraint("kind IN ('native', 'token', 'internal')", name="ck_transactions_kind"),
        sa.CheckConstraint(
            "provenance IN ('live_api', 'cached', 'mock_demo', 'mixed')",
            name="ck_transactions_provenance",
        ),
        sa.CheckConstraint("status IN ('success', 'failed')", name="ck_transactions_status"),
        sa.ForeignKeyConstraint(["raw_ref"], ["api_response_cache.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "chain",
            "tx_hash",
            "from_address",
            "to_address",
            "asset_symbol",
            "kind",
            name="uq_transactions_identity",
        ),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_transactions_from", ["chain", "from_address", "block_timestamp"], unique=False
        )
        batch_op.create_index("ix_transactions_hash", ["chain", "tx_hash"], unique=False)
        batch_op.create_index(
            "ix_transactions_to", ["chain", "to_address", "block_timestamp"], unique=False
        )

    op.create_table(
        "risk_entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chain", sa.String(length=16), nullable=False),
        sa.Column("address", sa.String(length=128), nullable=False),
        sa.Column("entity_kind", sa.String(length=32), nullable=False),
        sa.Column("entity_name", sa.String(length=255), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column("source_tier", sa.String(length=32), nullable=False),
        sa.Column("verification_status", sa.String(length=16), nullable=False),
        sa.Column("dataset_version_id", sa.Uuid(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "chain IN ('ethereum', 'tron', 'bitcoin', 'bnb', 'solana', 'polygon')",
            name="ck_risk_entities_chain",
        ),
        sa.CheckConstraint(
            "entity_kind IN ('mixer', 'bridge', 'gambling', 'darknet_market', 'sanctioned', 'scam_reported')",
            name="ck_risk_entities_kind",
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'low', 'medium', 'high')", name="ck_risk_entities_severity"
        ),
        sa.CheckConstraint(
            "source_tier IN ('official_vasp_published', 'sanctions_list', 'community_verified', 'community_unverified', 'demo_unverified')",
            name="ck_risk_entities_tier",
        ),
        sa.CheckConstraint(
            "verification_status IN ('verified', 'unverified', 'disputed')",
            name="ck_risk_entities_status",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["label_dataset_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "chain", "address", "entity_kind", "source", name="uq_risk_entities_identity"
        ),
    )
    with op.batch_alter_table("risk_entities", schema=None) as batch_op:
        batch_op.create_index("ix_risk_entities_lookup", ["chain", "address"], unique=False)

    op.create_table(
        "traces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.Column("subject_address", sa.String(length=128), nullable=False),
        sa.Column("subject_address_input", sa.String(length=128), nullable=False),
        sa.Column("chain", sa.String(length=16), nullable=False),
        sa.Column("hop_depth", sa.SmallInteger(), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("data_provenance", sa.String(length=16), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("truncation_reason", sa.String(length=255), nullable=True),
        sa.Column("nodes_expanded", sa.Integer(), nullable=False),
        sa.Column("api_calls_made", sa.Integer(), nullable=False),
        sa.Column("tx_analyzed_count", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("label_dataset_version_id", sa.Uuid(), nullable=False),
        sa.Column("scoring_config_version", sa.String(length=32), nullable=False),
        sa.Column("budget_config", app.database.types.JSONType(), nullable=False),
        sa.Column("engine_version", sa.String(length=32), nullable=False),
        sa.Column("review_decision", sa.String(length=32), nullable=False),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("error_message", sa.String(length=1024), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "chain IN ('ethereum', 'tron', 'bitcoin', 'bnb', 'solana', 'polygon')",
            name="ck_traces_chain",
        ),
        sa.CheckConstraint(
            "data_provenance IN ('live_api', 'cached', 'mock_demo', 'mixed')",
            name="ck_traces_provenance",
        ),
        sa.CheckConstraint("direction IN ('in', 'out')", name="ck_traces_direction"),
        sa.CheckConstraint(
            "review_decision IN ('pending', 'accepted', 'rejected', 'deeper_trace_requested')",
            name="ck_traces_review",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'partial', 'failed')",
            name="ck_traces_status",
        ),
        sa.CheckConstraint("hop_depth BETWEEN 1 AND 6", name="ck_traces_hop_depth"),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["label_dataset_version_id"],
            ["label_dataset_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("traces", schema=None) as batch_op:
        batch_op.create_index("ix_traces_case", ["case_id", "created_at"], unique=False)
        batch_op.create_index(
            "ix_traces_subject", ["chain", "subject_address", "created_at"], unique=False
        )

    op.create_table(
        "vasp_addresses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vasp_id", sa.Uuid(), nullable=False),
        sa.Column("chain", sa.String(length=16), nullable=False),
        sa.Column("address", sa.String(length=128), nullable=False),
        sa.Column("address_type", sa.String(length=32), nullable=True),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column("source_tier", sa.String(length=32), nullable=False),
        sa.Column("verification_status", sa.String(length=16), nullable=False),
        sa.Column("verified_by", sa.String(length=255), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reliability", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("dataset_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "address_type IN ('hot_wallet', 'deposit', 'cold_wallet', 'contract')",
            name="ck_vasp_addresses_addr_type",
        ),
        sa.CheckConstraint(
            "chain IN ('ethereum', 'tron', 'bitcoin', 'bnb', 'solana', 'polygon')",
            name="ck_vasp_addresses_chain",
        ),
        sa.CheckConstraint(
            "source_tier <> 'demo_unverified' OR verification_status = 'unverified'",
            name="ck_vasp_addresses_demo_is_unverified",
        ),
        sa.CheckConstraint(
            "source_tier IN ('official_vasp_published', 'sanctions_list', 'community_verified', 'community_unverified', 'demo_unverified')",
            name="ck_vasp_addresses_tier",
        ),
        sa.CheckConstraint(
            "verification_status <> 'verified' OR verified_at IS NOT NULL",
            name="ck_vasp_addresses_verified_needs_date",
        ),
        sa.CheckConstraint(
            "verification_status IN ('verified', 'unverified', 'disputed')",
            name="ck_vasp_addresses_status",
        ),
        sa.CheckConstraint(
            "reliability >= 0 AND reliability <= 1", name="ck_vasp_addresses_reliability_range"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["label_dataset_versions.id"],
        ),
        sa.ForeignKeyConstraint(["vasp_id"], ["vasps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "chain", "address", "vasp_id", "source", name="uq_vasp_addresses_identity"
        ),
    )
    with op.batch_alter_table("vasp_addresses", schema=None) as batch_op:
        batch_op.create_index("ix_vasp_addresses_lookup", ["chain", "address"], unique=False)
        batch_op.create_index("ix_vasp_addresses_tier", ["source_tier"], unique=False)
        batch_op.create_index("ix_vasp_addresses_vasp", ["vasp_id"], unique=False)

    op.create_table(
        "attributions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("vasp_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.SmallInteger(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=False),
        sa.Column("score_band", sa.String(length=16), nullable=False),
        sa.Column("score_type", sa.String(length=48), nullable=False),
        sa.Column("calibrated", sa.Boolean(), nullable=False),
        sa.Column("min_hop_distance", sa.SmallInteger(), nullable=False),
        sa.Column("matched_address_ids", app.database.types.JSONType(), nullable=False),
        sa.Column("interaction_tx_count", sa.Integer(), nullable=False),
        sa.Column("interaction_value", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("value_share", sa.Numeric(precision=9, scale=8), nullable=True),
        sa.Column("score_breakdown", app.database.types.JSONType(), nullable=False),
        sa.Column("evidence", app.database.types.JSONType(), nullable=False),
        sa.Column("risk_indicators", app.database.types.JSONType(), nullable=False),
        sa.Column("ml_score", sa.SmallInteger(), nullable=True),
        sa.Column("ml_model_version", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "score_band IN ('insufficient', 'low', 'moderate', 'strong', 'very_strong')",
            name="ck_attributions_band",
        ),
        sa.CheckConstraint(
            "score_type = 'heuristic_investigative_score'", name="ck_attributions_score_type"
        ),
        sa.CheckConstraint("score BETWEEN 0 AND 100", name="ck_attributions_score_range"),
        sa.ForeignKeyConstraint(["trace_id"], ["traces.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["vasp_id"],
            ["vasps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trace_id", "rank", name="uq_attributions_rank"),
        sa.UniqueConstraint("trace_id", "vasp_id", name="uq_attributions_vasp"),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("format", sa.String(length=8), nullable=False),
        sa.Column("report_ref", sa.String(length=64), nullable=False),
        sa.Column("payload", app.database.types.JSONType(), nullable=True),
        sa.Column("file_path", sa.String(length=512), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
        sa.Column("template_version", sa.String(length=32), nullable=False),
        sa.Column("generated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("format IN ('json', 'pdf')", name="ck_reports_format"),
        sa.ForeignKeyConstraint(
            ["generated_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["trace_id"], ["traces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_ref"),
    )
    op.create_table(
        "trace_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("address", sa.String(length=128), nullable=False),
        sa.Column("address_display", sa.String(length=128), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("hop_distance", sa.SmallInteger(), nullable=False),
        sa.Column("matched_vasp_id", sa.Uuid(), nullable=True),
        sa.Column("matched_vasp_address_id", sa.Uuid(), nullable=True),
        sa.Column("matched_risk_entity_id", sa.Uuid(), nullable=True),
        sa.Column("in_degree", sa.Integer(), nullable=True),
        sa.Column("out_degree", sa.Integer(), nullable=True),
        sa.Column("counterparty_count", sa.Integer(), nullable=True),
        sa.Column("value_in", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("value_out", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("expanded", sa.Boolean(), nullable=False),
        sa.Column("not_expanded_reason", sa.String(length=64), nullable=True),
        sa.Column("attrs", app.database.types.JSONType(), nullable=True),
        sa.CheckConstraint(
            "role IN ('subject', 'intermediate', 'vasp', 'risk_entity', 'contract')",
            name="ck_trace_nodes_role",
        ),
        sa.ForeignKeyConstraint(
            ["matched_risk_entity_id"],
            ["risk_entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["matched_vasp_address_id"],
            ["vasp_addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["matched_vasp_id"],
            ["vasps.id"],
        ),
        sa.ForeignKeyConstraint(["trace_id"], ["traces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trace_id", "address", name="uq_trace_nodes_address"),
    )
    with op.batch_alter_table("trace_nodes", schema=None) as batch_op:
        batch_op.create_index("ix_trace_nodes_hop", ["trace_id", "hop_distance"], unique=False)

    op.create_table(
        "trace_snapshot_refs",
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("api_response_cache_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["api_response_cache_id"], ["api_response_cache.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["trace_id"], ["traces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("trace_id", "api_response_cache_id"),
    )
    op.create_table(
        "disclosure_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("attribution_id", sa.Uuid(), nullable=False),
        sa.Column("vasp_id", sa.Uuid(), nullable=False),
        sa.Column("draft_ref", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("payload", app.database.types.JSONType(), nullable=False),
        sa.Column("payload_schema_version", sa.String(length=32), nullable=False),
        sa.Column("requested_information", app.database.types.JSONType(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("mode IN ('mock_demo')", name="ck_disclosure_mode"),
        sa.ForeignKeyConstraint(["attribution_id"], ["attributions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["trace_id"], ["traces.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["vasp_id"],
            ["vasps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_ref"),
    )
    op.create_table(
        "trace_edges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("from_node_id", sa.Uuid(), nullable=False),
        sa.Column("to_node_id", sa.Uuid(), nullable=False),
        sa.Column("dedup_key", sa.String(length=255), nullable=False),
        sa.Column("chain", sa.String(length=16), nullable=False),
        sa.Column("tx_hash", sa.String(length=128), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("asset_symbol", sa.String(length=32), nullable=False),
        sa.Column("asset_contract", sa.String(length=128), nullable=True),
        sa.Column("amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("block_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hop_index", sa.SmallInteger(), nullable=False),
        sa.Column("value_share", sa.Numeric(precision=9, scale=8), nullable=True),
        sa.Column("is_on_evidence_path", sa.Boolean(), nullable=False),
        sa.Column("attrs", app.database.types.JSONType(), nullable=True),
        sa.CheckConstraint(
            "chain IN ('ethereum', 'tron', 'bitcoin', 'bnb', 'solana', 'polygon')",
            name="ck_trace_edges_chain",
        ),
        sa.CheckConstraint("direction IN ('in', 'out')", name="ck_trace_edges_direction"),
        sa.ForeignKeyConstraint(["from_node_id"], ["trace_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_node_id"], ["trace_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trace_id"], ["traces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trace_id", "dedup_key", name="uq_trace_edges_dedup"),
    )
    with op.batch_alter_table("trace_edges", schema=None) as batch_op:
        batch_op.create_index(
            "ix_trace_edges_evidence", ["trace_id", "is_on_evidence_path"], unique=False
        )
        batch_op.create_index("ix_trace_edges_hop", ["trace_id", "hop_index"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trace_edges", schema=None) as batch_op:
        batch_op.drop_index("ix_trace_edges_hop")
        batch_op.drop_index("ix_trace_edges_evidence")

    op.drop_table("trace_edges")
    op.drop_table("disclosure_requests")
    op.drop_table("trace_snapshot_refs")
    with op.batch_alter_table("trace_nodes", schema=None) as batch_op:
        batch_op.drop_index("ix_trace_nodes_hop")

    op.drop_table("trace_nodes")
    op.drop_table("reports")
    op.drop_table("attributions")
    with op.batch_alter_table("vasp_addresses", schema=None) as batch_op:
        batch_op.drop_index("ix_vasp_addresses_vasp")
        batch_op.drop_index("ix_vasp_addresses_tier")
        batch_op.drop_index("ix_vasp_addresses_lookup")

    op.drop_table("vasp_addresses")
    with op.batch_alter_table("traces", schema=None) as batch_op:
        batch_op.drop_index("ix_traces_subject")
        batch_op.drop_index("ix_traces_case")

    op.drop_table("traces")
    with op.batch_alter_table("risk_entities", schema=None) as batch_op:
        batch_op.drop_index("ix_risk_entities_lookup")

    op.drop_table("risk_entities")
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_transactions_to")
        batch_op.drop_index("ix_transactions_hash")
        batch_op.drop_index("ix_transactions_from")

    op.drop_table("transactions")
    with op.batch_alter_table("token_transfers", schema=None) as batch_op:
        batch_op.drop_index("ix_token_transfers_to")
        batch_op.drop_index("ix_token_transfers_from")
        batch_op.drop_index("ix_token_transfers_contract")

    op.drop_table("token_transfers")
    op.drop_table("label_dataset_versions")
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_index("ix_cases_status_created")

    op.drop_table("cases")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_user")
        batch_op.drop_index("ix_audit_target")
        batch_op.drop_index("ix_audit_created")

    op.drop_table("audit_logs")
    op.drop_table("wallets")
    op.drop_table("vasps")
    op.drop_table("users")
    op.drop_table("ml_experiments")
    with op.batch_alter_table("api_response_cache", schema=None) as batch_op:
        batch_op.drop_index("ix_api_cache_expiry")

    op.drop_table("api_response_cache")
    # ### end Alembic commands ###
